version: '2'
services:
  zl-gnome-tiger:
    image: zl/dl-tigervnc:3.13.a
    container_name: zl_gnome_tiger
    restart: always
    privileged: true
    tty: true
    ports:
      - "22008:8888"
      - "22006:6006"
      - "22900:5900"
      - "22002:22"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
