version: '2'
services:
  zl:
    image: zl/deeplearning-ubuntu-desktop:12.28
    restart: always
    tty: true
    ports:
      - "8001:8888"
      - "6001:6006"
      - "8901:5901"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
  hzy:
    image: zl/deeplearning-ubuntu-desktop:12.28
    restart: always
    tty: true
    ports:
      - "8002:8888"
      - "6002:6006"
      - "8902:5901"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
