services:
  hzy:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/deeplearning-ubuntu-desktop:12.28
    ports:
    - 8002:8888
    - 6002:6006
    - 8902:5901
    restart: always
    tty: true
    volumes:
    - ~/hzy/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
  zl:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/deeplearning-ubuntu-desktop:12.28
    ports:
    - 8001:8888
    - 6001:6006
    - 8901:5901
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.57:
    external: true
