version: '2'
services:
  vpn:
    image: ikoula/docker-l2tp-ipsec-vpn
    container_name: docker-l2tp-ipsec-client-vpn
    network_mode: "host"
    privileged: true
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    cap_add:
      - NET_ADMIN
    env_file:
      - ./vpn.env
