version: '2'
services:
  zl-jupyterhub-singleuser:
    image: jupyterhub/singleuser
    container_name: zl_jupyterhub_singleuser
    privileged: true
    restart: always
    tty: true
    ports:
      - "58000:8000"
      - "58888:8888"
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
    environment:
      - USER_ID=22
      - USER=zhangli
      - HOME=/root
