
version: '3'
services:
  openwrt:
    # image: zoobab/openwrt-x86-attitude
    build:
      dockerfile: Dockerfile
      context: .
    container_name: openwrt
    hostname: OpenWrt
    ports:
      - "18022:22"
      - "18080:80"
    restart: always
    command: ["/sbin/init"]