services:
  hzy-caffe-torch:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/caffe-torch-gpu:12.27
    ports:
    - 8889:8888
    - 26007:6006
    restart: always
    tty: true
    volumes:
    - ~/hzy/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
  zl-caffe-torch:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/caffe-torch-gpu:12.27
    ports:
    - 8888:8888
    - 26006:6006
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.57:
    external: true
