version: '2'
services:
  zl:
    image: zl/caffe-torch-gpu:12.27
    restart: always
    tty: true
    ports:
      - "8001:8888"
      - "6001:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
  hzy:
    image: zl/caffe-torch-gpu:12.27
    restart: always
    tty: true
    ports:
      - "8002:8888"
      - "6002:6008"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
