services:
  zl-tensorflow:
    command: bash
    container_name: zl_tensorflow
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: tensorflow/tensorflow
    ports:
    - 28888:8888
    - 26006:6006
    privileged: true
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.57:
    external: true
