version: '2'
services:
  zl-gnome-supervisord:
    image: zl/dl-gnome:3.13.c
    container_name: zl_dl_gnome_supervisord
    restart: always
    tty: true
    ports:
      - "38121:22"
      - "38101:8888"
      - "36101:6006"
      - "30901:5901"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
