version: '2'
services:
  zl-dl-tightvnc:
#    image: zl/dl-tightvnc:3.18.a
    image: zl/dl-tightvnc:3.24.a
    container_name: zl_dl_tightvnc
    restart: always
    privileged: true
    tty: true
    ports:
      - "38222:22"
      - "38081:8888"
      - "36081:6006"
      - "38981:5901"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
      - /home/luoyulong/workspace:/workspace
