services:
  zl-dl-tightvnc:
    container_name: zl_dl_tightvnc
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/dl-tightvnc:3.24.a
    ports:
    - '38222:22'
    - 38081:8888
    - 36081:6006
    - 38981:5901
    privileged: true
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - /home/luoyulong/workspace:/workspace
    - nvidia_driver_375.39:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_375.39:
    external: true
