version: '2.3'
services:
  zl-dl-tightvnc:
<<<<<<< HEAD
    image: SXKJ:32775/zl-dev-dl-tightvnc:18.6.13.a
=======
    image: SXKJ:32775/zl-dev-dl-tightvnc:7.20.a
>>>>>>> 1833df4759907b9e3c274804439169a681071993
    container_name: zl_dev_dl_tightvnc
    restart: always
    privileged: true
    tty: true
    ports:
      - "33222:22"
      - "33081:8888"
      - "33086:6006"
      - "33981:5901"
      - "33989:8889"
      - "33881:8881"
<<<<<<< HEAD
    devices:
      - /dev/nvidia0
=======
    runtime: nvidia
>>>>>>> 1833df4759907b9e3c274804439169a681071993
    volumes:
      - /sxkj:/sxkj
      - ./supervisord.conf:/etc/supervisord.conf