version: '2'
services:
  zl-caffe-torch_:
    image: zl/caffe-torch:1.6.a
    container_name: zl_caffe_torch_
    restart: always
    tty: true
    ports:
      - "38888:8888"
      - "36006:6006"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
  hzy-caffe-torch_:
    image: zl/caffe-torch:1.6.a
    container_name: hzy_caffe_torch_
    restart: always
    tty: true
    ports:
      - "38889:8888"
      - "36007:6006"
    devices:
      - /dev/nvidia0
    volumes:
      - ~/hzy/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
      - ~/raychar/phpdocker/app/DeepAR_Backend/frontend/web/res/upload/ballreco:/root/BallReco
