services:
  hzy-caffe-torch_:
    container_name: hzy_caffe_torch_
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/caffe-torch:1.6.a
    ports:
    - 38889:8888
    - 36007:6006
    restart: always
    tty: true
    volumes:
    - ~/hzy/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - ~/raychar/phpdocker/app/DeepAR_Backend/frontend/web/res/upload/ballreco:/root/BallReco
    - nvidia_driver_367.57:/usr/local/nvidia:ro
  zl-caffe-torch_:
    container_name: zl_caffe_torch_
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/caffe-torch:1.6.a
    ports:
    - 38888:8888
    - 36006:6006
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - nvidia_driver_367.57:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_367.57:
    external: true
