version: '2'
services:
  zl-jupyterhub:
    image: zl/jupyterhub:3.8.a
    container_name: zl_jupyterhub
    privileged: true
    restart: always
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ~/zhangli/dl-data:/root/dl-data
      - ~/sxwl-dataset:/root/sxwl-dataset
