version: '3'
services:
  zl-fastai:
    image: zl/dev-fastai:11.12.a
    container_name: zl_dev_fastai
    restart: always
    privileged: true
    tty: true
    ports:
      - "35222:22"
      - "35081:8888"
      - "35086:6006"
      - "35981:5901"
      - "35989:8889"
      - "35881:8881"
    #runtime: nvidia
    volumes:
      - /sxkj/nas:/data/nas
      - ./start.conf:/etc/supervisor/conf.d/start.conf
      - ./supervisord.conf:/etc/supervisord.conf
      - ./start.sh:/opt/start.sh