<<<<<<< HEAD
version: '2'
services:
  zl-fastai:
    image: zl/dev-fastai:6.7.a
=======
version: '2.3'
services:
  zl-fastai:
    image: SXKJ:32775/zl-dev-fastai:7.20.a
>>>>>>> 1833df4759907b9e3c274804439169a681071993
    container_name: zl_dev_fastai
    restart: always
    privileged: true
    tty: true
    ports:
      - "35222:22"
      - "35081:8888"
      - "35086:6006"
      - "35981:5901"
      - "35989:8889"
      - "35881:8881"
<<<<<<< HEAD
    devices:
      - /dev/nvidia0
=======
    # devices:
    #   - /dev/nvidia0
    runtime: nvidia
>>>>>>> 1833df4759907b9e3c274804439169a681071993
    volumes:
      - /sxkj/nas:/data/nas
      - ./supervisord.conf:/etc/supervisord.conf
      - ./start.sh:/opt/start.sh