services:
  zl-fastai:
    container_name: zl_dev_fastai
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    image: zl/dev-fastai:6.7.a
    ports:
    - '35222:22'
    - 35081:8888
    - 35086:6006
    - 35981:5901
    - 35989:8889
    - 35881:8881
    privileged: true
    restart: always
    tty: true
    volumes:
    - /sxkj/nas:/data/nas
    - ./supervisord.conf:/etc/supervisord.conf
    - ./start.sh:/opt/start.sh
    - nvidia_driver_396.24.02:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_396.24.02:
    external: true
