services:
  zl-dl-tightvnc:
    container_name: zl_dev_dl_tightvnc
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: zl/dev-dl-tightvnc:4.19.aa
    ports:
    - '34222:22'
    - 34081:8888
    - 34086:6006
    - 34981:5901
    privileged: true
    restart: always
    tty: true
    volumes:
    - ~/zhangli/dl-data:/root/dl-data
    - ~/sxwl-dataset:/root/sxwl-dataset
    - /home/luoyulong/workspace:/workspace
    - nvidia_driver_375.39:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_375.39:
    external: true
