version: '2'
services:
  git:
    image : gogs/gogs:latest
    restart : always
    container_name : sx1080_git_server
    depends_on:
      - postgres
    volumes:
      - ./gogs-server:/data
    ports:
      - "12222:22"
      - "18888:3000"
    links:
      - postgres
  postgres:
    image: kiasaki/alpine-postgres
    container_name: gogs_postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5433:5432"
